#define RA_INTEGRATION_VERSION "0.999" 
#define RA_INTEGRATION_VERSION_MAJOR 0 
#define RA_INTEGRATION_VERSION_MINOR 071 
#define RA_INTEGRATION_VERSION_REVISION 10 
#define RA_INTEGRATION_VERSION_MODIFIED 0 
#define RA_INTEGRATION_VERSION_PRODUCT "0.071-rapidjson_update" 
