//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RA_Shared.rc
//
#define IDD_RA_RICHPRESENCE             1100
#define IDD_RA_MEMBOOKMARK              1101
#define IDC_RA_RICHPRESENCERESULTTEXT   1102
#define IDC_RA_LBX_ADDRESSES            1103
#define IDC_RA_OPENPAGE                 1104
#define IDC_RA_DEL_BOOKMARK             1105
#define IDC_RA_CLEAR_CHANGE             1106
#define IDC_RA_MOVE_BOOKMARK_UP         1107
#define IDC_RA_BROWSE                   1108
#define IDC_RA_MOVE_BOOKMARK_DOWN       1109
#define IDC_RA_SAVEBOOKMARK             1110
#define IDC_RA_LOADBOOKMARK             1111
#define IDC_RA_RESULTS_BACK             1112
#define IDC_RA_RESULTS_FORWARD          1113
#define IDC_RA_RESULTS_REMOVE           1114
#define IDC_RA_SEARCHTYPE               1115
#define IDC_RA_SYSTEMNAME               1116
#define IDC_RA_LINK                     1117
#define IDC_RA_GAMENAME                 1118
#define IDC_RA_SELECT_ACHIEVEMENTS      1119
#define IDC_RA_PROBLEMHEADER            1120
#define IDC_RA_BADGE_SPIN               1121
#define IDC_RA_DISPLAY_TRIGGER          1122
#define IDC_RA_SCREENSHOT_TRIGGER       1123
#define IDC_RA_DISPLAY_LBOARD_START     1124
#define IDC_RA_DISPLAY_LBOARD_CANCEL    1125
#define IDC_RA_DISPLAY_LBOARD_VALUE     1126
#define IDC_RA_DISPLAY_LBOARD_SCOREBOARD 1127
#define IDC_RA_LOCATION                 1128
#define IDC_RA_SCREENSHOT_LOCATION      1129
#define IDC_RA_DISPLAY_MASTERY          1130
#define IDC_RA_SCREENSHOT_MASTERY       1131
#define IDC_RA_RESULTS_BOOKMARK         1132
#define IDC_RA_FILTER_VALUE             1133
#define IDC_RA_APPLY_FILTER             1134
#define IDC_RA_RESET_FILTER             1135
#define IDC_RA_RESULT_COUNT             1136
#define IDC_RA_NOTE_TEXT                1137
#define IDC_RA_ADD_NOTE                 1138
#define IDC_RA_DELETE_NOTE              1139
#define IDC_RA_RESULTS                  1140
#define IDC_RA_SEARCHRANGES             1141
#define IDC_RA_SEARCHRANGE              1142
#define IDC_RA_COMPARISON               1143
#define IDC_RA_SPECIAL_FILTER           1144
#define IDC_RA_CONTINUOUS_FILTER        1145
#define IDC_RA_RESULT_FILTER            1146
#define IDC_RA_ADDRESS                  1147
#define IDC_RA_VIEW_CODENOTES           1148
#define IDC_RA_MEMVIEW_8BIT             1149
#define IDC_RA_MEMVIEW_16BIT            1150
#define IDC_RA_MEMVIEW_32BIT            1151
#define IDC_RA_MEMVIEWER                1152
#define IDC_RA_MEMBITS                  1153
#define IDC_RA_MEMBITS_TITLE            1154
#define IDC_RA_RESULT_PAGE              1155
#define IDC_RA_GBX_SEARCH               1156
#define IDC_RA_GBX_FILTER               1157
#define IDC_RA_GBX_RESULTS              1158
#define IDC_RA_GBX_NOTES                1159
#define IDD_RA_MEMORY                   1501
#define IDD_RA_ACHIEVEMENTS             1502
#define IDD_RA_ACHIEVEMENTEDITOR        1503
#define IDD_RA_LOGIN                    1504
#define IDD_RA_GAMETITLESEL             1505
#define IDD_RA_CODENOTES                1506
#define IDD_RA_LEADERBOARDEDITOR        1507
#define IDD_RA_REPORTBROKENACHIEVEMENTS 1508
#define IDD_RA_GAMELIBRARY              1509
#define IDD_RA_ROMCHECKSUM              1510
#define IDD_RA_OVERLAYSETTINGS          1511
#define IDC_RA_UPLOAD_BADGE             1517
#define IDC_RA_ADDBOOKMARK              1518
#define IDC_RA_INFO_GG                  1519
#define IDC_RA_HELP                     1521
#define IDC_RA_CHEEVOPIC                1522
#define IDC_RA_REVERTSELECTED           1523
#define IDC_RA_RESET_ACH                1524
#define IDC_RA_CHK_SHOW_DECIMALS        1526
#define IDC_RA_DELETECOND               1527
#define IDC_RA_COPYCOND                 1528
#define IDC_RA_ACH_ID                   1529
#define IDC_RA_DEL_ACH                  1530
#define IDC_RA_PASTECOND                1530
#define IDC_RA_CHKACHPROCESSINGACTIVE   1531
#define IDC_RA_GOTOWIKI                 1532
#define IDC_RA_GAMEHASH                 1533
#define IDC_RA_NUMACH                   1534
#define IDC_RA_PASSWORD                 1535
#define IDC_RA_POINT_TOTAL              1535
#define IDC_RA_SAVEPASSWORD             1536
#define IDC_RA_ACTIVE_CORE              1537
#define IDC_RA_ACTIVE_UNOFFICIAL        1538
#define IDC_RA_ACTIVE_LOCAL             1539
#define IDC_RA_LISTACHIEVEMENTS         1540
#define IDC_RA_ACH_TITLE                1541
#define IDC_RA_ADD_ACH                  1542
#define IDC_RA_ACH_POINTS               1543
#define IDC_RA_CLONE_ACH                1544
#define IDC_RA_LBX_CONDITIONS           1545
#define IDC_RA_ACH_AUTHOR               1546
#define IDC_RA_ADDCOND                  1547
#define IDC_RA_ACH_DESC                 1548
#define IDC_RA_USERNAME                 1549
#define IDC_RA_DOWNLOAD_ACH             1550
#define IDC_RA_COMMIT_ACH               1551
#define IDC_RA_PROMOTE_ACH              1552
#define IDC_RA_WATCH                    1557
#define IDC_RA_CHK_ACH_ACTIVE           1562
#define IDC_RA_GAMETITLE                1563
#define IDC_RA_BADGENAME                1564
#define IDC_RA_KNOWNGAMES               1565
#define IDC_RA_CHECKSUM                 1566
#define IDC_RA_MOVECONDUP               1568
#define IDC_RA_ACTIVATE_ALL_ACH         1574
#define IDC_RA_ACH_GROUP                1575
#define IDC_RA_ACH_DELGROUP             1576
#define IDC_RA_ACH_ADDGROUP             1577
#define IDC_RA_PROGRESSINDICATORS       1578
#define IDC_RA_CHK_ACH_PAUSE_ON_TRIGGER 1585
#define IDC_RA_REPORTBROKENACHIEVEMENTSLIST 1586
#define IDC_RA_CHK_ACH_PAUSE_ON_RESET   1586
#define IDC_RA_BROKENACHIEVEMENTREPORTCOMMENT 1587
#define IDC_RA_PROBLEMTYPE1             1588
#define IDC_RA_PROBLEMTYPE2             1589
#define IDC_RA_COMMENT_HEADER           1590
#define IDC_RA_RESCAN                   1591
#define IDC_RA_LBX_GAMELIST             1592
#define IDC_RA_ROMDIR                   1593
#define IDC_RA_GLIB_NAME                1594
#define IDC_RA_PICKROMDIR               1595
#define IDC_RA_REFRESH                  1596
#define IDC_RA_SCANNERFOUNDINFO         1597
#define IDC_RA_ROMCHECKSUMTEXT          1598
#define IDC_RA_COPYCHECKSUMCLIPBOARD    1599
#define IDC_RA_MOVECONDDOWN             1605
#define IDC_RA_ROMCHECKSUMHEADER        1606
#define IDM_RA_MENUSTART                1700
#define IDM_RA_RETROACHIEVEMENTS        1700
#define IDM_RA_OVERLAYSETTINGS          1701
#define IDM_RA_FILES_MEMORYBOOKMARKS    1703
#define IDM_RA_FILES_ACHIEVEMENTS       1704
#define IDM_RA_FILES_MEMORYFINDER       1705
#define IDM_RA_FILES_LOGIN              1706
#define IDM_RA_FILES_LOGOUT             1707
#define IDM_RA_FILES_ACHIEVEMENTEDITOR  1708
#define IDM_RA_FILES_LEADERBOARDEDITOR  1709
#define IDM_RA_HARDCORE_MODE            1710
#define IDM_RA_REPORTBROKENACHIEVEMENTS 1711
#define IDM_RA_GETROMCHECKSUM           1712
#define IDM_RA_OPENUSERPAGE             1713
#define IDM_RA_OPENGAMEPAGE             1714
#define IDM_RA_SCANFORGAMES             1715
#define IDM_RA_PARSERICHPRESENCE        1716
#define IDM_RA_TOGGLELEADERBOARDS       1717
#define IDM_RA_NON_HARDCORE_WARNING     1718
#define IDM_RA_MENUEND                  1739

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
